Minimizing the code so the project expose the problem clearly during compilation.
StartCameraActivity.java:10: error: package android.support.v4.content
does not exist
import android.support.v4.content.FileProvider;

StartCameraActivity.java:84: error: cannot find symbol
                Uri photoURI = FileProvider.getUriForFile(this,